spring:
  application:
    name: boardVer3
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board2024_v3
    username: root
    password: green502

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  version: '@springdoc.version@'
  swagger-ui:

    path: /swagger
    operations-sorter: method # operation 정렬 (alpha: url 주소 기준(default), method: http method 기준 정렬)
    use-root-path: false # root 경로에서 Swagger UI 화면 표시 여부
    try-it-out-enabled: false # Try it out Direct 활성화 여부
    display-request-duration: true # try it out 을 했을 때 request duration(처리 소요시간) 을 추가로 찍어줌
    cache:
      disabled: true
    show-extensions: true
    show-common-extensions: true
    doc-expansion: none #펼치기
    default-models-expand-depth: 10
    default-model-rendering: model

  api-docs:
    resolve-schema-properties: true # X
    resolve-extensions-properties: true # X
  remove-broken-reference-definitions: false


server:
  forward-headers-strategy: framework